---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: Windows-2012r2

suites:
  - name: default
    run_list:

      - recipe[workstation-cookbook::default]
      - recipe[hyperv::default]
    attributes:
